---
version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: posSstsxemple12
  web:
    build: ../../
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    hostname: web
    volumes:
      - ../../:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  sidekiq:
    build: ../../
    command: "bundle exec sidekiq"
    volumes:
      - ../../:/myapp
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis
